export const USER_IN_SESSION = 'USER_IN_SESSION';
export const GET_LOGIN = 'GET_LOGIN';
export const REGISTER_NEW_USER = 'REGISTER_NEW_USER';
export const GET_MY_COURSES = 'GET_MY_COURSES';
export const LOGOUT_USER= 'LOGOUT_USER';
